src/board/beans/User.java
package board.beans;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private String login_id;
    private String password;
    private String name;
    private int branch_id;
    private String branch_name;
    private int position_id;
    private String position_name;
    private boolean is_stopped;
    private Date created_at;
    private Date updated_at;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getLoginId() {
		return login_id;
	}
	public void setLoginId(String login_id) {
		this.login_id = login_id;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getBranchId() {
		return branch_id;
	}
	public void setBranchId(int branch_id) {
		this.branch_id = branch_id;
	}
	public int getPositionId() {
		return position_id;
	}
	public void setPositionId(int position_id) {
		this.position_id = position_id;
	}
	public boolean getIsStopped() {
		return is_stopped;
	}
	public void setIsStopped(boolean is_stopped) {
		this.is_stopped = is_stopped;
	}
	public Date getCreatedDate() {
		return created_at;
	}
	public void setCreatedDate(Date created_at) {
		this.created_at = created_at;
	}
	public Date getUpdatedDate() {
		return updated_at;
	}
	public void setUpdatedDate(Date updated_at) {
		this.updated_at = updated_at;
	}
	public String getPositionName() {
		return position_name;
	}
	public void setPositionName(String positionName) {
		this.position_name = positionName;
	}
	public String getBranchName() {
		return branch_name;
	}
	public void setBranchName(String branchName) {
		this.branch_name = branchName;
	}
}

src/board/controller/HomeServlet.java
package board.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import board.beans.Comment;
import board.beans.Post;
import board.beans.User;
import board.service.CommentService;
import board.service.PostService;
@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    @Override
    protected void doGet(HttpServletRequest request,
        HttpServletResponse response) throws IOException, ServletException {
		String searchByDateStart = request.getParameter("searchByDateStart");
		String searchByDateEnd = request.getParameter("searchByDateEnd");
		String searchByCategory = null;
		if ( StringUtils.isBlank(searchByDateStart) ) {
			searchByDateStart = "";
		}
		if ( StringUtils.isBlank(searchByDateEnd) ) {
			searchByDateEnd = "";
		}
		try {
			searchByCategory = new String (request.getParameter("searchByCategory").getBytes("ISO-8859-1"));
		} catch(NullPointerException e) {
			searchByCategory = "";
		}
		request.setAttribute("searchByDateStart", searchByDateStart);
		request.setAttribute("searchByDateEnd", searchByDateEnd);
		request.setAttribute("searchByCategory", searchByCategory);
		HttpSession session = request.getSession();
		List<Post> posts = null;
		List<Comment> comments = new CommentService().getComment();
		User user = (User) session.getAttribute("loginUser");
		if ( searchByCategory.length() > 10 ) {
		    session.setAttribute("errorComments", "カテゴリ名は10文字以下で検索してください");
		    posts = new PostService().getPost("", "", "");
		} else {
			posts = new PostService().getPost(searchByDateStart, searchByDateEnd, searchByCategory);
		}
		request.setAttribute("posts", posts);
		request.setAttribute("comments", comments);
		request.setAttribute("loginUser", user);
		if ( user.getBranchId() != 1 ||
			 user.getPositionId() != 1 ) {
			request.setAttribute("isManager", "false");
		}
		request.getRequestDispatcher("home.jsp").forward(request, response);
    }
}

src/board/controller/LoginServlet.java
package board.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import board.beans.User;
import board.service.LoginService;

@WebServlet(urlPatterns = { "/login"})
public class LoginServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {
        HttpSession session = request.getSession();
        session.setAttribute("errorMessages", session.getAttribute("errorMessages"));
        request.getRequestDispatcher("login.jsp").forward(request, response);
    }
    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {
        String loginId = request.getParameter("loginId");
        String password = request.getParameter("password");
        HttpSession session = request.getSession();
        String idPattern = "[0-9a-zA-Z]{6,20}";
        String pwPattern = "^[ -~]{6,20}$";
        if (!loginId.matches(idPattern) ||
        	!password.matches(pwPattern) ) {
            List<String> messages = new ArrayList<String>();
            messages.add("ログインに失敗しました。");
            request.setAttribute("loginId",loginId );
            session.setAttribute("errorMessages", messages);
            request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }
        LoginService loginService = new LoginService();
        User user = loginService.login(loginId, password);
        if (user != null &&
        	!user.getIsStopped()) {
        	session.removeAttribute("loginUser");
            session.setAttribute("loginUser", user);
            List<String> messages = new ArrayList<String>();
            session.setAttribute("errorMessages", messages);
            response.sendRedirect("./");
        } else {
            List<String> messages = new ArrayList<String>();
            messages.add("ログインに失敗しました。");
            request.setAttribute("loginId",loginId );
            session.setAttribute("errorMessages", messages);
            request.getRequestDispatcher("login.jsp").forward(request, response);
        }
    }
}

src/board/controller/PostServlet.java
package board.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import board.beans.Post;
import board.beans.User;
import board.service.PostService;
@WebServlet(urlPatterns = { "/post" })
public class PostServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {
        request.getRequestDispatcher("post.jsp").forward(request, response);
    }
    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {
        HttpSession session = request.getSession();
        List<String> posts = new ArrayList<String>();
        if (isValid(request, posts) == true) {
            User user = (User) session.getAttribute("loginUser");
            Post post = new Post();
            post.setTitle(request.getParameter("title"));
            post.setText(request.getParameter("text"));
            post.setCategory(request.getParameter("category"));
            post.setUserId(String.valueOf(user.getId()));
            new PostService().register(post);
            response.sendRedirect("./");
        } else {
            session.setAttribute("errorMessages", posts);
            request.setAttribute("title", request.getParameter("title"));
            request.setAttribute("text", request.getParameter("text"));
            request.setAttribute("category", request.getParameter("category"));
            request.getRequestDispatcher("post.jsp").forward(request, response);
        }
    }

    private boolean isValid(HttpServletRequest request, List<String> posts) {
    	String title = request.getParameter("title");
        String text = request.getParameter("text");
        String category = request.getParameter("category");
        if (StringUtils.isBlank(title) == true) {
            posts.add("件名を入力してください");
        }
        if (StringUtils.isBlank(text) == true) {
            posts.add("本文を入力してください");
        }
        if (StringUtils.isBlank(category) == true) {
            posts.add("カテゴリーを入力してください");
        }
        if (30 < title.length()) {
        	posts.add("件名を30文字以下で入力してください");
        }
        if (1000 < text.length()) {
        	posts.add("本文を1000文字以下で入力してください");
        }
        if (10 < category.length()) {
        	posts.add("カテゴリーを10文字以下で入力してください");
        }
        if (posts.size() == 0) {
            return true;
        } else {
            return false;
        }
    }
}

src/board/controller/SignUpServlet.java
package board.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import board.beans.Branch;
import board.beans.Position;
import board.beans.User;
import board.service.BranchService;
import board.service.PositionService;
import board.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {
		HttpSession session = request.getSession();
        if ( ((User) session.getAttribute("loginUser")).getBranchId() != 1 ||
       		 ((User) session.getAttribute("loginUser")).getPositionId() != 1) {
        	response.sendRedirect("./");
        	return;
        }
		List<Branch> branches = new BranchService().getBranch();
        List<Position> positions = new PositionService().getPosition();
        request.setAttribute("branches", branches);
        request.setAttribute("positions", positions);
        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }
    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {
        List<String> messages = new ArrayList<String>();
        HttpSession session = request.getSession();
        User user = getInputUser(request);
        if (isValid(request, messages) == true) {
            new UserService().register(user);
            response.sendRedirect("userManager");
        } else {
            session.setAttribute("errorMessages", messages);
    		List<Branch> branches = new BranchService().getBranch();
            List<Position> positions = new PositionService().getPosition();
            request.setAttribute("login_id", user.getLoginId());
            request.setAttribute("name", user.getName());
            request.setAttribute("branches", branches);
            request.setAttribute("positions", positions);
            request.setAttribute("selectedBranchId", Integer.valueOf(request.getParameter("branch_id")));
            request.setAttribute("selectedPositionId", Integer.valueOf(request.getParameter("position_id")));
            request.getRequestDispatcher("signup.jsp").forward(request, response);
        }
    }
    private User getInputUser(HttpServletRequest request)
            throws IOException, ServletException {
        User inputUser = new User();
        inputUser.setLoginId(request.getParameter("login_id"));
        inputUser.setPassword(request.getParameter("password"));
        inputUser.setName(request.getParameter("name"));
        inputUser.setBranchId(Integer.valueOf(request.getParameter("branch_id")));
        inputUser.setPositionId(Integer.valueOf(request.getParameter("position_id")));
        inputUser.setIsStopped(false);
        return inputUser;
    }
    private boolean isValid(HttpServletRequest request, List<String> messages) {
        String loginId = request.getParameter("login_id");
        String password = request.getParameter("password");
        String confirm = request.getParameter("confirm");
        String name = request.getParameter("name");
        String branchId = request.getParameter("branch_id");
        String positionId = request.getParameter("position_id");
        String idPattern = "[0-9a-zA-Z]{6,20}";
        String pwPattern = "^[ -~]{6,20}$";
        if (StringUtils.isBlank(loginId)) {
            messages.add("ログインIDを入力してください");
        }
        if (!loginId.matches(idPattern)) {
            messages.add("ログインIDは半角英数字の6文字以上20文字以下で入力してください");
        }
        //loginIdの重複チェック
        UserService userService = new UserService();
        User user = userService.getUserByLoginId(loginId);
        if ( user != null ) {
            messages.add("入力されたログインIDは既に使用されています");
        }
        if (!StringUtils.isBlank(password) &&
            	StringUtils.isBlank(confirm)) {
                messages.add("パスワード(確認用)を入力してください");
        }
        if (StringUtils.isBlank(password) &&
         	!StringUtils.isBlank(confirm)) {
            messages.add("パスワードを入力してください");
        }
        if (!password.matches(pwPattern)) {
            messages.add("パスワードは記号を含む全ての半角文字6文字以上20文字以下で入力してください");
        }
        if ( !StringUtils.isBlank(password) &&
                !StringUtils.isBlank(confirm) &&
                !password.matches(confirm) ) {
            messages.add("「パスワード」と「パスワード(確認用)」に入力された値が異なっています");
        }
        if (StringUtils.isBlank(name) ) {
        	messages.add("名前を入力してください");
        }
        if (name.length() > 10 ) {
        	messages.add("名前は10文字以下で入力してください");
        }
		List<Branch> branches = new BranchService().getBranch();
        List<Position> positions = new PositionService().getPosition();
        if ( branchId.equals("1") &&
        	 !(positionId.equals("1") || positionId.equals("2")) ) {
        	messages.add(
        		"所属支店で「" +
        		branches.get(0).getName() +
        		"」を選択された場合、「" +
        		positions.get(0).getName() +
        		"」か「" +
        		positions.get(1).getName() +
        		"」を選択してください");
        } else if ( !branchId.equals("1") &&
        		(positionId.equals("1") || positionId.equals("2")) ) {
        	messages.add(
            		"所属支店で「" +
            		branches.get(0).getName() +
            		"」以外を選択された場合、「" +
            		positions.get(0).getName() +
            		"」か「" +
            		positions.get(1).getName() +
            		"」以外を選択してください");
        }
        if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }
}

src/board/controller/UserManagerServlet.java
package board.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import board.beans.User;
import board.service.UserService;

@WebServlet(urlPatterns = { "/userManager" })
public class UserManagerServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {
		HttpSession session = request.getSession();
        if ( ((User) session.getAttribute("loginUser")).getBranchId() != 1 ||
       		 ((User) session.getAttribute("loginUser")).getPositionId() != 1) {
        	response.sendRedirect("./");
        	return;
        }
		List<User> users = new UserService().getUsersWithBranchesNameAndPositionsName();
		request.setAttribute("users", users);
        request.setAttribute("loginUser", ((User)session.getAttribute("loginUser")).getId());
        request.getRequestDispatcher("/userManager.jsp").forward(request, response);
    }
}

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html>
<html>
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	    <link href="./style.css" rel="stylesheet" type="text/css" />
	    <script type="text/javascript">
	    function commentDeleteCheck(){
	        if(window.confirm('コメントを削除しますか？')){
	            return true; // 「OK」時は送信を実行
	        } else {
	            return false; // 送信を中止
	        }
	    }
	    function postDeleteCheck(){
	        if(window.confirm('投稿を削除しますか？')){
	            return true; // 「OK」時は送信を実行
	        } else {
	            return false; // 送信を中止
	        }
	    }
	    </script>
	    <title>ホーム画面</title>
	</head>
	<body>
	    <c:if test="${ not empty errorComments }">
	        <div class="errorMessages">
	                <c:forEach items="${errorComments}" var="errorComments">
	                    <c:out value="${errorComments}" />
	                </c:forEach>
	        </div>
	        <c:remove var="errorComments" scope="session"/>
	    </c:if>
	    <div class="header">
	    	${loginUser.name}さん
	    </div>
	    <div class="left-column">
	        <div class="menu">
	            <a href="post">新規投稿</a><br />
	            <c:if test="${ empty isManager }">
	                <a href="userManager">ユーザー管理</a><br />
	            </c:if>
	            ---<br />
	            <a href="login">ログアウト</a>
	        </div>
		    <div class="search-box">
		        <!-- 絞込検索ボックスブロック -->
		        [検索]
		        <form name="searchButton" action="index.jsp" method="get">
		            <!-- 日付検索 -->
		            期間指定：<br />
		            <input type="date" name="searchByDateStart" value="${searchByDateStart}"></input><br />
		            　　　～<br />
		            <input type="date" name="searchByDateEnd" value="${searchByDateEnd}"></input><br />
		            <!-- カテゴリ検索 -->
		            <br />
		            カテゴリ指定：<br />
		             <input type="text" name="searchByCategory" value="${searchByCategory}"></input><br />
		             <br />
		             <!-- 検索ボタン -->
		             <input type="submit" value="検索">
	             </form>
	         </div>
        </div>
        <div class="main-column">
         <!-- 投稿ブロック -->
	            <div class="posts">
	                <c:forEach items="${posts}" var="post">
	                    <div class="post">
	                        <b>件名：</b>
	                        <span class="title"><c:out value="${post.title}" /></span><br />
	                        <b>本文：<br /></b>
	                        <span class="text"><c:forEach var="str" items="${fn:split(post.text,'
')}" ><c:out value="${str}" /><br /></c:forEach></span><br />
	                        <b>カテゴリー：</b>
	                        <span class="category"><c:out value="${post.category}" /></span><br />
	                       <b>投稿者：</b>
	                        <span class="name"><c:out value="${post.name}" /></span><br />
	                        <b>投稿日時：</b>
	                        <fmt:formatDate value="${post.createdAt}" pattern="yyyy.MM.dd HH:mm:ss" /><br />
	                        <c:if test="${post.userId == loginUser.id}">
	                            <form name="deletePost" action="deletePost" method="post" onSubmit="return postDeleteCheck()">
	                                <input type="hidden" name="postId" value="${post.id}">
	                                <input type="submit" value="投稿削除">
	                            </form>
	                        </c:if>
	                   </div>
	                        <!-- コメントブロック -->
	                        <c:forEach items="${comments}" var="comment">
	                            <c:if test="${post.id == comment.postId }">
	                   <div class="comments">
	                                <b>コメント：<br /></b>
	                                    <span class="comment">
	                                    <c:forEach var="str" items="${fn:split(comment.text,'
')}" ><c:out value="${str}" /><br /></c:forEach></span><br />
	                                <b>登録者：</b>
	                                    <span class="commentUsername"><c:out value="${comment.username}" /></span><br />
	                                <b>登録日時：</b>
	                                    <fmt:formatDate value="${comment.createdAt}" pattern="yyyy/MM/dd HH:mm:ss" /><br />
	                                <c:if test="${comment.userId == loginUser.id}">
	                                    <form name="deleteComment" action="deleteComment" method="post"  onSubmit="return commentDeleteCheck()">
	                                        <input type="hidden" name="commentId" value="${comment.id}">
	                                        <input type="submit" value="コメント削除">
	                                    </form>
	                                </c:if>
	                   </div>
	                            </c:if>
	                        </c:forEach>
	                   <div class="comment-box">
	                        <!-- コメント入力ボックスブロック -->
	                        <form action="comment" method="post">
	                            <b>コメント入力：<br /></b>
	                            <input type="hidden" name="postId" value="${post.id}">
	                            <textarea name="comment" cols="100" rows="4" class="comment"></textarea><br />
	                            <input type="submit" value="コメント">(500文字まで)
	                        </form>
	                    </div>
	                </c:forEach>
	            </div>
	        <br />
	        <div class="copyright"> Copyright(c) Fukuda Naoki</div>
	    </div>
	</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
		<link href="./style.css" rel="stylesheet" type="text/css">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ログイン画面</title>
    </head>
    <body>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>
            <form action="login" method="post"><br />
                <label for="loginId">ログインID</label>
         		<c:if test="${ not empty loginId }">
                	<input name="loginId" id="loginId" value="<%=request.getAttribute("loginId") %>"/> <br />
       			</c:if>
         		<c:if test="${ empty loginId }">
                	<input name="loginId" id="loginId" value=""/> <br />
       			</c:if>

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <input type="submit" value="ログイン" /> <br />
            </form>
			<br />
            <div class="copyright"> Copyright(c) FukudaNaoki</div>
        </div>
    </body>
</html>

WebContent/post.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<link href="./style.css" rel="stylesheet" type="text/css">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>新規投稿画面</title>
</head>
<body>
	<c:if test="${ not empty errorMessages }">
		<div class="errorMessages">
			<ul>
				<c:forEach items="${errorMessages}" var="message">
					<li><c:out value="${message}" />
				</c:forEach>
			</ul>
		</div>
		<c:remove var="errorMessages" scope="session"/>
	</c:if>
	<div class="head-menu">
		<a href="./">戻る</a>
	</div>
	<div class="main-contents">
		<c:if test="${ not empty loginUser }">
			<div class="form-area">
				<form action="post" method="post">
					件名<br />
					<input name="title" class="title" value="${title}"/><br />
					本文<br />
					<textarea name="text" cols="100" rows="10" class="text"><c:if test="${ not empty text}"><%=request.getParameter("text") %></c:if></textarea><br />
					カテゴリー<br />
					<input name="category" class="category" value="${category}"/><br />
					<br />
					<input type="submit" value="投稿"><br />(1000文字まで)
				</form>
			</div>
		</c:if>
	</div>
	<br />
	<div class="copyright">
		Copyright(c) FukudaNaoki
	</div>
</body>
</html>

WebContent/userManager.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC>
<html>
<head>
	<link href="./style.css" rel="stylesheet" type="text/css">
	<script type="text/javascript">
		function check(){
			if(window.confirm('ユーザーの有効/無効を切り替えますか？')){
				return true; // 「OK」時は送信を実行
			} else {
				return false; // 送信を中止
			}
		}
	</script>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>ユーザー管理画面</title>
</head>
<body>
	<c:if test="${ not empty errorMessages }">
		<div class="errorMessages">
			<ul>
				<c:forEach items="${errorMessages}" var="message">
					<li><c:out value="${message}" />
				</c:forEach>
			</ul>
		</div>
		<c:remove var="errorMessages" scope="session" />
	</c:if>
	<div class="head-menu">
		<a href="./">戻る</a>
		<a href="signup">ユーザー登録</a>
	</div>
	<br />
	<div class="users">
		<table border="1">
			<tr>
				<th>ログインID</th><th>名称</th><th>支店</th><th>部署・役職</th><th>稼働状況</th><th>管理</th>
			</tr>
			<c:forEach items="${users}" var="user">
				<tr>
					<td>
						<c:out value="${user.loginId}" />
					</td>
					<td>
						<c:out value="${user.name}" />
					</td>
					<td>
						<c:out value="${user.branchName}" />
					</td>
					<td>
						<c:out value="${user.positionName}" />
					</td>
					<td>
						<form action="switch" method="post" onSubmit="return check()">
							<c:if test="${user.id != loginUser}">
								<c:if test="${user.isStopped == true}">
									<input type="hidden" name="user_id" value="${user.id}">
									<input type="submit" value="停止中">
								</c:if>
								<c:if test="${user.isStopped == false}">
									<input type="hidden" name="user_id" value="${user.id}">
									<input type="submit" value="稼動中">
								</c:if>
							</c:if>
						</form>
					</td>
					<td>
						<a href="settings?user_id=${user.id}">編集</a>
					</td>
				</tr>
			</c:forEach>
		</table>
		<br />
	</div>
	<div class="copyright">
		Copyright(c) FukudaNaoki
	</div>
</body>
</html>